### ISSUE TITLE
how does this work ...?

### ISSUE THREAD

**Issue by brogalan-blora** [MohamedYasser97/ArtsyBot#2]
![Screenshot_20210207-131726](https://user-images.githubusercontent.com/78091059/107138426-ec6b1500-6946-11eb-9b4f-83e132e05560.png)
Even though the script is running, there are no recent tweets ...
🙏🙏🙏

**Comment by yasserror** [comment]
This is so old😅
It worked by fetching images from Reddit's json endpoints (you can't leave
subreddits.js empty).

So the case may be that you left that file empty or that Reddit changed
things since then. I'll put this on my To-Do list😃

**Comment by yasserror** [comment]
I tried it and it worked just fine. Make sure you added your application's token in config.js and just the subreddit names in "subreddits.js" without the "r/"
![image](https://user-images.githubusercontent.com/30673997/107143485-02c0a300-693e-11eb-9c10-273d4bc4a41c.png)

**Comment by brogalan-blora** [comment]
sorry I don't know where to put the subreddit ..
Sorry I just learned ...
🙏🙏🙏

**Comment by yasserror** [comment]
Like this
![image](https://user-images.githubusercontent.com/30673997/107146509-7e781b00-6951-11eb-93e7-01924509e907.png)
in the subreddits.js file..those are real subreddit names from Reddit

**Comment by brogalan-blora** [comment]
thank you very much i have found my mistake ...
